services:
  localization:
    build: &localization_build
      context: ..
      dockerfile: docker/localization/localization.Dockerfile
      cache_from:
        - "${LOCALIZATION_IMAGE:?}:${TAG}"
        - "${LOCALIZATION_IMAGE:?}:main"
      args:
        BASE_IMAGE: ${BASE_IMAGE_OVERRIDE-}
    image: "${LOCALIZATION_IMAGE:?}:${TAG}"
    profiles: [deploy]
    command: /bin/bash -c "ros2 launch nav2_gps_waypoint_follower_demo gazebo_gps_world.launch.py"
    volumes:
      - ${MONO_DIR}/src/localization:/root/ament_ws/src/nav2_gps_waypoint_follower_demo
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=waffle
    network_mode: "host"
    privileged: true

  localization_dev:
    build: *localization_build
    image: "${LOCALIZATION_IMAGE:?}:dev_${TAG}"
    command: tail -F anything
    profiles: [develop]
    volumes:
      - ${MONO_DIR}/src/localization:/root/ament_ws/src/nav2_gps_waypoint_follower_demo